config/routes.rb
Rails.application.routes.draw do
  resources :filmes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   get '/', to: 'filmes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/filme.rb
class Filme < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/filmes_controller.rb
class FilmesController < ApplicationController
  before_action :set_filme, only: [:show, :edit, :update, :destroy]

  # GET /filmes
  # GET /filmes.json
  def index
    @filmes = Filme.all
  end

  # GET /filmes/1
  # GET /filmes/1.json
  def show
  end

  # GET /filmes/new
  def new
    @filme = Filme.new
  end

  # GET /filmes/1/edit
  def edit
  end

  # POST /filmes
  # POST /filmes.json
  def create
    @filme = Filme.new(filme_params)

    respond_to do |format|
      if @filme.save
        format.html { redirect_to @filme, notice: 'O filme foi criado com sucesso!' }
        format.json { render :show, status: :created, location: @filme }
      else
        format.html { render :new }
        format.json { render json: @filme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filmes/1
  # PATCH/PUT /filmes/1.json
  def update
    respond_to do |format|
      if @filme.update(filme_params)
        format.html { redirect_to @filme, notice: 'Filme atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @filme }
      else
        format.html { render :edit }
        format.json { render json: @filme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filmes/1
  # DELETE /filmes/1.json
  def destroy
    @filme.destroy
    respond_to do |format|
      format.html { redirect_to filmes_url, notice: 'Filme removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filme
      @filme = Filme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filme_params
      params.require(:filme).permit(:titulo, :classificacao, :lancamento, :sinopse)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/filmes_helper.rb
module FilmesHelper
end

app/views/filmes/_form.html.erb
<%= form_for(filme) do |f| %>
  <% if filme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(filme.errors.count, "error") %> prohibited this filme from being saved:</h2>

      <ul>
      <% filme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"Título" %>
    <%= f.text_field :titulo %>
  </div>

  <div class="field">
    <%= f.label :"Classificação" %>
    <%= f.select :classificacao, options_for_select([["1", "Um"], ["2", "Dois"], ["3", "Tres"], ["4", "Quatro"], ["5", "Cinco"]]) %>
  </div>

  <div class="field">
    <%= f.label :"Lançamento" %>
    <%= f.datetime_select :lancamento %>
  </div>

  <div class="field">
    <%= f.label :sinopse %>
    <%= f.text_area :sinopse %>
  </div>

  <div class="actions">
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/filmes/edit.html.erb
<table width="100%" height=50px>
	<tr>
		<th id="t01">Rotten Potatoes!</th>
	</tr>
</table>
	<h1>Editando o filme <%= @filme.titulo %></h1>

<%= render 'form', filme: @filme %>

<%= link_to 'Mostrar', @filme %> |
<%= link_to 'Voltar', filmes_path %>

app/views/filmes/index.html.erb
<%= stylesheet_link_tag "abc.css" %>

<p id="notice"><%= notice %></p>
<table width="100%" height=50px>
	<tr>
		<th id="t01">Rotten Potatoes!</th>
	</tr>
</table>
<table width="100%" cellspacing="1">
  <thead>
    <tr bgcolor="black">
      <th id="t02" width="500px">Título</th>
      <th id="t02" width="120px"><center>Classificação<center></th>
      <th id="t02" width="250px"><center>Lançamento</center></th>
      <th id="t02" width="100px"><center>Sinopse</center></th>
      <th id="t02" colspan="3">Modificar</th>
    </tr>
  </thead>

  <tbody>
    <% @filmes.each do |filme| %>
      <tr height=20px>
        <td><%= filme.titulo %></td>
        <td><center><%= filme.classificacao %></center></td>
        <td><center><%= filme.lancamento %><center></td>
        <td><center><%= link_to 'Mostrar', filme %></center></td>
        <td><center><%= link_to 'Editar', edit_filme_path(filme) %></center></td>
        <td><center><%= link_to 'Remover', filme, method: :delete, data: { confirm: 'Remover?' } %></center></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo filme', new_filme_path %>

app/views/filmes/new.html.erb
<table width="100%" height=50px>
	<tr>
		<th id="t01">Rotten Potatoes!</th>
	</tr>
</table>
<h1>Novo filme</h1>

<%= render 'form', filme: @filme %>

<%= link_to 'Voltar', filmes_path %>

app/views/filmes/show.html.erb
<table width="100%" height=50px>
	<tr>
		<th id="t01">Rotten Potatoes!</th>
	</tr>
</table>

<p>
  <h1><%= @filme.titulo %></h1>
</p>

<p>
  <li><strong>Classificação:</strong>
  <%= @filme.classificacao %> estrelas</li>
</p>

<p>
  <li><strong>Lançamento:</strong>
  <%= @filme.lancamento %></li>
</p>

<p>
  <h3><strong>Sinopse:<br></strong></h3>
  <%= @filme.sinopse %>
</p>

<%= link_to 'Editar', edit_filme_path(@filme) %> |
<%= link_to 'Voltar', filmes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ineboy Potatoes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>